
version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: echo_mongodb
    environment:
      - MONGO_INITDB_DATABASE=crud_echo
      - MONGO_INITDB_ROOT_USERNAME=izzaturrahman19
      - MONGO_INITDB_ROOT_PASSWORD=mindtrex
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-data:/data/db
    ports:
      - "27017:27017"
      - "27018:27018"
      - "27019:27019" 
